【ITGD-4766】Icon組件
dio-chu/interview-todo-list pull request #3
Opened 2024-08-27 06:30 UTC by dio-chu

2024-08-27 09:06 UTC, simpsons01 reviewed
建議可以多拆一個IconButton讓Icon元件邏輯可以更單純，可能會像這樣
```
<template>
  <button
    :disable="disable"
  >
    <icon :src="icon" :size="size" />
  </button>
</template>
<script>
export default {
   props: {
       disable: { 
           type: Boolean,
           default: false
       },
       icon: {
           type: String,
           required: true
       },
      size: {
         type: String,
         required: true
      }
   }
}
</script>
```

2024-08-27 09:15 UTC, simpsons01 requested changes

2024-08-27 09:15 UTC, simpsons01 commented on src/common/icon/Icon.vue
> +      validator: (value) => ["lg", "md", "sm"].includes(value),
新增一個 
`common/icon/components/IconSize` 去定義 IconSize的列舉

2024-08-28 06:06 UTC, dio-chu commented
2024/08/28
主要PR FIle：
[feature:PR icon修改](https://github.com/dio-chu/interview-todo-list/pull/3/commits/541d109fb5a0490ee5e9f79128b6dc2d5261f98f)

2024-08-29 03:32 UTC, simpsons01 approved these changes

2024-08-29 03:34 UTC, merged