【ITGD-4748】List Header
dio-chu/interview-todo-list pull request #6
Opened 2024-08-28 15:50 UTC by dio-chu

主要 review 項目
[feature:add ListHeader component](https://github.com/dio-chu/interview-todo-list/commit/d2b482e114e19b3a7cff9901b4388171134d37e0)

2024-08-30 07:11 UTC, dio-chu commented
@simpsons01 
2024 08/30
修改list header
[feat(ITGD-4748):PR修改 props名稱](https://github.com/dio-chu/interview-todo-list/pull/6/commits/aded65220c2ff43f6f2c1b296352ed9feaf0a844)

2024-09-02 05:59 UTC, simpsons01 requested changes

2024-09-02 05:59 UTC, simpsons01 commented on src/components/list/header/ListHeader.vue
> +    },
上有示意這個元件實作`ICheckbox`，但是沒有看到實作`ICheckbox`的`props.modelValue`與emit `update:modelValue`事件，可以考慮思考是要實作`ICheckbox`還是拔掉`ICheckbox`

2024-09-02 07:01 UTC, dio-chu commented on src/components/list/header/ListHeader.vue
> +    },
@simpsons01  修改完成！
[feat:remove ICheckbox Inheritance](https://github.com/dio-chu/interview-todo-list/pull/6/commits/7ad047052d5731c163dd87d28d6f9c9be6f923b7)

2024-09-02 08:45 UTC, simpsons01 approved these changes

2024-09-02 09:56 UTC, merged